config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView

app_name = MaterialsConfig.name


urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, EmailVerify, ActivationInvalid

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='genpass'),
    path('verify/<str:uidb64>/<token>/', EmailVerify.as_view(), name='verify_acc'),
    path('activation_invalid/', ActivationInvalid.as_view(), name='activation_invalid'),
]

materials/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Materials(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='materials/', **NULLABLE, verbose_name='превью')
    creation_date = models.DateField(auto_now=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

materials/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from materials.models import Materials


class MaterialCreateView(LoginRequiredMixin, CreateView):
    model = Materials
    # permission_required = 'materials.add_post'
    fields = ('title', 'content', 'is_published', 'preview',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class MaterialListView(ListView):
    model = Materials
    extra_context = {
        'title': 'Материалы'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class MaterialDetailView(DetailView):
    model = Materials
    template_name = 'materials/materials_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class MaterialUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Materials
    permission_required = 'materials.change_post'
    fields = ('title', 'content', 'is_published', 'preview',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Materials
    permission_required = 'materials.delete_post'
    success_url = reverse_lazy('materials:list')

materials/templates/materials/materials_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'materials:list' %}" class="btn btn-warning">Нет</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.title }}</h1>
    <img class="card-img-top"
    src="{{ object.preview|mymedia }}">
    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
        <li>Заголовок: {{ object.price }}</li>
        <li>Ссылка: {{object.slug}}</li>
        <li>Содержимое: {{object.content}}</li>
        <li>Дата изготовления: {{object.creation_date}}</li>
        <li>Опубликовано: {{object.is_published}}</li>
        <li>Просмотры: {{object.views}}</li>
    </ul>
</div>
{% endblock %}

materials/templates/materials/materials_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a class="btn btn-warning" href="{% url 'materials:list' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12 mb-2">
    {% if user.is_authenticated %}
       <a class="btn btn-btn btn-primary" href="{% url 'materials:create' %}">Добавить блог</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>- Содержимое: {{ object.content }}</li>
                <li>- Дата изготовления:</li>
                <li> {{ object.creation_date }}</li>
            </ul>
            <nav class="ms-5">
                <a href="{% url 'materials:view' object.pk %}" type="button"
                   class="btn btn-lg btn-sm btn-outline-secondary">Подробнее</a>
                {% if perms.materials.change_post %}
                <a href="{% url 'materials:edit' object.pk %}" type="button"
                   class="btn btn-lg btn-sm btn-outline-secondary">Изменить</a>
                {% endif %}
                {% if perms.materials.delete_post %}
                <a href="{% url 'materials:delete' object.pk %}" type="button"
                   class="btn btn-lg btn-sm btn-outline-danger">Удалить</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}