catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', cache_page(60)(contacts), name='contacts'),
    path('', cache_page(60)(ProductListView.as_view()), name='product_list'),
    path('category/', cache_page(60)(CategoryListView.as_view()), name='product_category_list'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_card'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete_product')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, EmailVerify, ActivationInvalid

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='genpass'),
    path('verify/<str:uidb64>/<token>/', EmailVerify.as_view(), name='verify_acc'),
    path('activation_invalid/', ActivationInvalid.as_view(), name='activation_invalid'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='категория')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    last_change = models.DateField(verbose_name='дата последнего изменения', **NULLABLE)
    date_create = models.DateField(verbose_name='дата создания', auto_now=True)
    price = models.IntegerField(verbose_name='цена')
    preview_image = models.ImageField(verbose_name='превью', **NULLABLE)
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.CASCADE, **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE,)
    is_public = models.BooleanField(default=False, verbose_name='публикация', **NULLABLE)

    def __str__(self):
        return f'{self.name}({self.category}): {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, **NULLABLE, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=100, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    version_sign = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.product} Номер версии:{self.version_name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

catalog/forms.py
from django import forms

from catalog.models import Product, Version, Category


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):

    banned_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for word in self.banned_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('В названии есть запрещенные слова!')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in self.banned_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('В описании есть запрещенные слова!')
        return cleaned_data


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_list, get_product_versions_list


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        version_list = Version.objects.all()
        context_data['formset'] = version_list
        context_data['title'] = 'Каталог'
        return context_data


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['versions'] = get_product_versions_list(self.object.pk)
        return context_data


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    permission_required = 'catalog.add_product'
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    permission_required = 'catalog.change_product'
    form_class = ProductForm
    # fields = ('name', 'category', 'price', 'preview_image')
    success_url = reverse_lazy('catalog:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_list = Version.objects.filter(pk=self.object.pk)
        context_data['formset'] = version_list
        return context_data


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'catalog/product_category_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_category_list()
        context_data['title'] = 'Категории'
        return context_data


@login_required
def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} {phone}: {message}')

    context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contacts.html', context)




# def product_card(request, pk):
#     product_item = Product.objects.get(pk=pk)
#
#     context = {
#         'object_list': Product.objects.filter(pk=pk),
#         'title': f'Товар : {product_item.name}',
#     }
#     return render(request, 'catalog/product_detail.html', context)

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
<div class="container">
    <div class="row text-start">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/card.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    {% for object in object_list %}
    <img class="card-img-top"
    src="{{ object.preview_image|mymedia }}">
    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
        <li>Цена: {{ object.price }}</li>
        <li>Категория: {{ object.category }}</li>
        <li>Дата изготовления: {{ object.date_create }}</li>
        <li>Описание: {{ object.description }}</li>
    </ul>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-lg-9 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Страна</td>
                    <td>USA</td>
                </tr>
                <tr>
                    <td class="w-25">ИНН</td>
                    <td>91-1144442</td>
                </tr>
                <tr>
                    <td class="w-25">Адрес</td>
                    <td>Redmond,WA,98052-6399</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
        </div>
        <div class="card-body">
            <form method="post" action="" class="form-floating">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name">Имя</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                           required>
                </div>
                <div class="mb-3">
                    <label for="phone">Телефон</label>
                    <input type="number" name="phone" class="form-control" id="phone"
                           placeholder="Контактный телефон" required>
                </div>
                <div class="mb-3">
                    <label for="message">Сообщение</label>
                    <textarea name="message" class="form-control" id="message"
                              placeholder="Сообщение" required></textarea>
                </div>
                <input type="submit" class="btn btn-lg btn-block btn-outline-primary" value="Отправить">
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title"> Цена: ₽{{ object.price }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>- Категория: {{ object.category }}</li>
                <li>- Дата изготовления:</li>
                <li> {{ object.date_create }}</li>
                <li>- Краткое описание:</li>
                <li> {{ object.description|limit_symbols }}</li>
            </ul>
            <nav class="ms-5">
                <a class="p-2 btn btn-outline-primary">Купить</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_card' object.pk %}">Подробнее</a>

            </nav>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12 mb-2"></div>
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top"
             src="{{ object.preview_img|mymedia }}"
             alt="Card image cap">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
        </div>
        <div class="card-body">
            <a href="#" type="button"
               class="btn btn-lg btn-sm btn-outline-primary">Подробнее</a>
            {% if perms.catalog.change_product %}
            <a href="#" type="button"
               class="btn btn-lg btn-sm btn-outline-secondary">Изменить</a>
            {% endif %}
            {% if perms.catalog.delete_product %}
            <a href="#" type="button"
               class="btn btn-lg btn-sm btn-outline-danger">Удалить</a>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить товар "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.name }}</h1>
    <img class="card-img-top"
         src="{{ object.preview_image|mymedia }}">
    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
        <li>Цена: {{ object.price }}</li>
        <li>Категория: {{ object.category }}</li>
        <li>Дата изготовления: {{ object.date_create }}</li>
        <li>Описание: {{ object.description|default:'Без описания' }}</li>
        {% for form in versions %}
        {% if form.version_sign %}
        <h5>Активная версия</h5>
        <li>- Номер версии: {{ form.version_number }}</li>
        <li>- Название версии: {{ form.version_name }}</li>
        {% endif %}
        {% endfor %}
    </ul>

</div>
<div>
    <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Назад</a>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Добавление продукта</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a class="btn btn-warning" href="{% url 'catalog:product_list' %}">Отмена</a>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Версия продукта</h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a class="btn btn-warning" href="{% url 'catalog:product_list' %}">Отмена</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12 mb-2">
    {% if perms.catalog.add_product %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить товар</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title"> Цена: ₽{{ object.price }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>- Категория: {{ object.category }}</li>
                <li>- Дата изготовления:</li>
                <li>- Владелец: {{object.owner|default:"Без владельца"}}</li>
                <li> {{ object.date_create }}</li>
                <li>- Краткое описание:</li>
                <li> {{ object.description|limit_symbols }}</li>
                {% for form in formset %}
                {% if form.product == object and form.version_sign == True %}
                <h5>Активная версия</h5>
                <li>- Номер версии: {{ form.version_number }}</li>
                <li>- Название версии: {{ form.version_name }}</li>
                {% endif %}
                {% endfor %}
            </ul>
            <nav class="ms-5">
                <a class="p-2 btn btn-outline-primary">Купить</a>
                <a href="{% url 'catalog:product_card' object.pk %}"
                   class="p-2 btn btn-outline-primary">Подробнее</a>
                {% if perms.catalog.change_product %}
                <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                   class="btn btn-lg btn-sm btn-outline-secondary">Изменить</a>
                {% endif %}
                {% if perms.catalog.delete_product %}
                <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                   class="btn btn-lg btn-sm btn-outline-danger">Удалить</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}